/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ApiGenerateTitleRouteImport } from './routes/api/generate-title'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiProjectsIndexRouteImport } from './routes/api/projects/index'
import { Route as ApiConversationsIndexRouteImport } from './routes/api/conversations/index'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'
import { Route as ApiConversationsIdRouteImport } from './routes/api/conversations/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiProjectsIdAddConversationRouteImport } from './routes/api/projects/$id.add-conversation'
import { Route as ApiConversationsIdMessagesRouteImport } from './routes/api/conversations/$id.messages'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateTitleRoute = ApiGenerateTitleRouteImport.update({
  id: '/api/generate-title',
  path: '/api/generate-title',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIndexRoute = ApiConversationsIndexRouteImport.update({
  id: '/api/conversations/',
  path: '/api/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/api/projects/$id',
  path: '/api/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIdRoute = ApiConversationsIdRouteImport.update({
  id: '/api/conversations/$id',
  path: '/api/conversations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdAddConversationRoute =
  ApiProjectsIdAddConversationRouteImport.update({
    id: '/add-conversation',
    path: '/add-conversation',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)
const ApiConversationsIdMessagesRoute =
  ApiConversationsIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiConversationsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-title': typeof ApiGenerateTitleRoute
  '/chat/$id': typeof ChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/$id': typeof ApiConversationsIdRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/conversations': typeof ApiConversationsIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/projects/$id/add-conversation': typeof ApiProjectsIdAddConversationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-title': typeof ApiGenerateTitleRoute
  '/chat/$id': typeof ChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/$id': typeof ApiConversationsIdRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/conversations': typeof ApiConversationsIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/projects/$id/add-conversation': typeof ApiProjectsIdAddConversationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-title': typeof ApiGenerateTitleRoute
  '/chat/$id': typeof ChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/$id': typeof ApiConversationsIdRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/projects/$id/add-conversation': typeof ApiProjectsIdAddConversationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/login'
    | '/new'
    | '/projects'
    | '/api/chat'
    | '/api/generate-title'
    | '/chat/$id'
    | '/api/auth/$'
    | '/api/conversations/$id'
    | '/api/projects/$id'
    | '/api/conversations'
    | '/api/projects'
    | '/api/conversations/$id/messages'
    | '/api/projects/$id/add-conversation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats'
    | '/login'
    | '/new'
    | '/projects'
    | '/api/chat'
    | '/api/generate-title'
    | '/chat/$id'
    | '/api/auth/$'
    | '/api/conversations/$id'
    | '/api/projects/$id'
    | '/api/conversations'
    | '/api/projects'
    | '/api/conversations/$id/messages'
    | '/api/projects/$id/add-conversation'
  id:
    | '__root__'
    | '/'
    | '/chats'
    | '/login'
    | '/new'
    | '/projects'
    | '/api/chat'
    | '/api/generate-title'
    | '/chat/$id'
    | '/api/auth/$'
    | '/api/conversations/$id'
    | '/api/projects/$id'
    | '/api/conversations/'
    | '/api/projects/'
    | '/api/conversations/$id/messages'
    | '/api/projects/$id/add-conversation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  ProjectsRoute: typeof ProjectsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateTitleRoute: typeof ApiGenerateTitleRoute
  ChatIdRoute: typeof ChatIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConversationsIdRoute: typeof ApiConversationsIdRouteWithChildren
  ApiProjectsIdRoute: typeof ApiProjectsIdRouteWithChildren
  ApiConversationsIndexRoute: typeof ApiConversationsIndexRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-title': {
      id: '/api/generate-title'
      path: '/api/generate-title'
      fullPath: '/api/generate-title'
      preLoaderRoute: typeof ApiGenerateTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/': {
      id: '/api/conversations/'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/api/projects/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id': {
      id: '/api/conversations/$id'
      path: '/api/conversations/$id'
      fullPath: '/api/conversations/$id'
      preLoaderRoute: typeof ApiConversationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/add-conversation': {
      id: '/api/projects/$id/add-conversation'
      path: '/add-conversation'
      fullPath: '/api/projects/$id/add-conversation'
      preLoaderRoute: typeof ApiProjectsIdAddConversationRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/conversations/$id/messages': {
      id: '/api/conversations/$id/messages'
      path: '/messages'
      fullPath: '/api/conversations/$id/messages'
      preLoaderRoute: typeof ApiConversationsIdMessagesRouteImport
      parentRoute: typeof ApiConversationsIdRoute
    }
  }
}

interface ApiConversationsIdRouteChildren {
  ApiConversationsIdMessagesRoute: typeof ApiConversationsIdMessagesRoute
}

const ApiConversationsIdRouteChildren: ApiConversationsIdRouteChildren = {
  ApiConversationsIdMessagesRoute: ApiConversationsIdMessagesRoute,
}

const ApiConversationsIdRouteWithChildren =
  ApiConversationsIdRoute._addFileChildren(ApiConversationsIdRouteChildren)

interface ApiProjectsIdRouteChildren {
  ApiProjectsIdAddConversationRoute: typeof ApiProjectsIdAddConversationRoute
}

const ApiProjectsIdRouteChildren: ApiProjectsIdRouteChildren = {
  ApiProjectsIdAddConversationRoute: ApiProjectsIdAddConversationRoute,
}

const ApiProjectsIdRouteWithChildren = ApiProjectsIdRoute._addFileChildren(
  ApiProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  ProjectsRoute: ProjectsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateTitleRoute: ApiGenerateTitleRoute,
  ChatIdRoute: ChatIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConversationsIdRoute: ApiConversationsIdRouteWithChildren,
  ApiProjectsIdRoute: ApiProjectsIdRouteWithChildren,
  ApiConversationsIndexRoute: ApiConversationsIndexRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
