/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewRouteImport } from './routes/new'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ApiGenerateTitleRouteImport } from './routes/api/generate-title'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateTitleRoute = ApiGenerateTitleRouteImport.update({
  id: '/api/generate-title',
  path: '/api/generate-title',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-title': typeof ApiGenerateTitleRoute
  '/chat/$id': typeof ChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-title': typeof ApiGenerateTitleRoute
  '/chat/$id': typeof ChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-title': typeof ApiGenerateTitleRoute
  '/chat/$id': typeof ChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/new'
    | '/projects'
    | '/api/chat'
    | '/api/generate-title'
    | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats'
    | '/new'
    | '/projects'
    | '/api/chat'
    | '/api/generate-title'
    | '/chat/$id'
  id:
    | '__root__'
    | '/'
    | '/chats'
    | '/new'
    | '/projects'
    | '/api/chat'
    | '/api/generate-title'
    | '/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRoute
  NewRoute: typeof NewRoute
  ProjectsRoute: typeof ProjectsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateTitleRoute: typeof ApiGenerateTitleRoute
  ChatIdRoute: typeof ChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-title': {
      id: '/api/generate-title'
      path: '/api/generate-title'
      fullPath: '/api/generate-title'
      preLoaderRoute: typeof ApiGenerateTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRoute,
  NewRoute: NewRoute,
  ProjectsRoute: ProjectsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateTitleRoute: ApiGenerateTitleRoute,
  ChatIdRoute: ChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
