/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as SIdRouteImport } from './routes/s/$id'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ApiShareRouteImport } from './routes/api/share'
import { Route as ApiGenerateTitleRouteImport } from './routes/api/generate-title'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiProjectsIndexRouteImport } from './routes/api/projects/index'
import { Route as ApiConversationsIndexRouteImport } from './routes/api/conversations/index'
import { Route as ApiProjectsMetadataRouteImport } from './routes/api/projects/metadata'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'
import { Route as ApiConversationsIdRouteImport } from './routes/api/conversations/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiProjectsIdConversationsRouteImport } from './routes/api/projects/$id.conversations'
import { Route as ApiProjectsIdAddConversationRouteImport } from './routes/api/projects/$id.add-conversation'
import { Route as ApiConversationsIdShareRouteImport } from './routes/api/conversations/$id.share'
import { Route as ApiConversationsIdProjectsRouteImport } from './routes/api/conversations/$id.projects'
import { Route as ApiConversationsIdMessagesRouteImport } from './routes/api/conversations/$id.messages'

const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareRoute = ApiShareRouteImport.update({
  id: '/api/share',
  path: '/api/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateTitleRoute = ApiGenerateTitleRouteImport.update({
  id: '/api/generate-title',
  path: '/api/generate-title',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIndexRoute = ApiConversationsIndexRouteImport.update({
  id: '/api/conversations/',
  path: '/api/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsMetadataRoute = ApiProjectsMetadataRouteImport.update({
  id: '/api/projects/metadata',
  path: '/api/projects/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/api/projects/$id',
  path: '/api/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIdRoute = ApiConversationsIdRouteImport.update({
  id: '/api/conversations/$id',
  path: '/api/conversations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdConversationsRoute =
  ApiProjectsIdConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)
const ApiProjectsIdAddConversationRoute =
  ApiProjectsIdAddConversationRouteImport.update({
    id: '/add-conversation',
    path: '/add-conversation',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)
const ApiConversationsIdShareRoute = ApiConversationsIdShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => ApiConversationsIdRoute,
} as any)
const ApiConversationsIdProjectsRoute =
  ApiConversationsIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ApiConversationsIdRoute,
  } as any)
const ApiConversationsIdMessagesRoute =
  ApiConversationsIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiConversationsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/shared': typeof SharedRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-title': typeof ApiGenerateTitleRoute
  '/api/share': typeof ApiShareRoute
  '/chat/$id': typeof ChatIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/s/$id': typeof SIdRoute
  '/share/$id': typeof ShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/$id': typeof ApiConversationsIdRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/projects/metadata': typeof ApiProjectsMetadataRoute
  '/api/conversations': typeof ApiConversationsIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/projects': typeof ApiConversationsIdProjectsRoute
  '/api/conversations/$id/share': typeof ApiConversationsIdShareRoute
  '/api/projects/$id/add-conversation': typeof ApiProjectsIdAddConversationRoute
  '/api/projects/$id/conversations': typeof ApiProjectsIdConversationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/shared': typeof SharedRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-title': typeof ApiGenerateTitleRoute
  '/api/share': typeof ApiShareRoute
  '/chat/$id': typeof ChatIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/s/$id': typeof SIdRoute
  '/share/$id': typeof ShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/$id': typeof ApiConversationsIdRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/projects/metadata': typeof ApiProjectsMetadataRoute
  '/api/conversations': typeof ApiConversationsIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/projects': typeof ApiConversationsIdProjectsRoute
  '/api/conversations/$id/share': typeof ApiConversationsIdShareRoute
  '/api/projects/$id/add-conversation': typeof ApiProjectsIdAddConversationRoute
  '/api/projects/$id/conversations': typeof ApiProjectsIdConversationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/shared': typeof SharedRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-title': typeof ApiGenerateTitleRoute
  '/api/share': typeof ApiShareRoute
  '/chat/$id': typeof ChatIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/s/$id': typeof SIdRoute
  '/share/$id': typeof ShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/$id': typeof ApiConversationsIdRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/projects/metadata': typeof ApiProjectsMetadataRoute
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/projects': typeof ApiConversationsIdProjectsRoute
  '/api/conversations/$id/share': typeof ApiConversationsIdShareRoute
  '/api/projects/$id/add-conversation': typeof ApiProjectsIdAddConversationRoute
  '/api/projects/$id/conversations': typeof ApiProjectsIdConversationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/login'
    | '/new'
    | '/projects'
    | '/shared'
    | '/api/chat'
    | '/api/generate-title'
    | '/api/share'
    | '/chat/$id'
    | '/project/$id'
    | '/s/$id'
    | '/share/$id'
    | '/api/auth/$'
    | '/api/conversations/$id'
    | '/api/projects/$id'
    | '/api/projects/metadata'
    | '/api/conversations'
    | '/api/projects'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/projects'
    | '/api/conversations/$id/share'
    | '/api/projects/$id/add-conversation'
    | '/api/projects/$id/conversations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats'
    | '/login'
    | '/new'
    | '/projects'
    | '/shared'
    | '/api/chat'
    | '/api/generate-title'
    | '/api/share'
    | '/chat/$id'
    | '/project/$id'
    | '/s/$id'
    | '/share/$id'
    | '/api/auth/$'
    | '/api/conversations/$id'
    | '/api/projects/$id'
    | '/api/projects/metadata'
    | '/api/conversations'
    | '/api/projects'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/projects'
    | '/api/conversations/$id/share'
    | '/api/projects/$id/add-conversation'
    | '/api/projects/$id/conversations'
  id:
    | '__root__'
    | '/'
    | '/chats'
    | '/login'
    | '/new'
    | '/projects'
    | '/shared'
    | '/api/chat'
    | '/api/generate-title'
    | '/api/share'
    | '/chat/$id'
    | '/project/$id'
    | '/s/$id'
    | '/share/$id'
    | '/api/auth/$'
    | '/api/conversations/$id'
    | '/api/projects/$id'
    | '/api/projects/metadata'
    | '/api/conversations/'
    | '/api/projects/'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/projects'
    | '/api/conversations/$id/share'
    | '/api/projects/$id/add-conversation'
    | '/api/projects/$id/conversations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  ProjectsRoute: typeof ProjectsRoute
  SharedRoute: typeof SharedRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateTitleRoute: typeof ApiGenerateTitleRoute
  ApiShareRoute: typeof ApiShareRoute
  ChatIdRoute: typeof ChatIdRoute
  ProjectIdRoute: typeof ProjectIdRoute
  SIdRoute: typeof SIdRoute
  ShareIdRoute: typeof ShareIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConversationsIdRoute: typeof ApiConversationsIdRouteWithChildren
  ApiProjectsIdRoute: typeof ApiProjectsIdRouteWithChildren
  ApiProjectsMetadataRoute: typeof ApiProjectsMetadataRoute
  ApiConversationsIndexRoute: typeof ApiConversationsIndexRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share': {
      id: '/api/share'
      path: '/api/share'
      fullPath: '/api/share'
      preLoaderRoute: typeof ApiShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-title': {
      id: '/api/generate-title'
      path: '/api/generate-title'
      fullPath: '/api/generate-title'
      preLoaderRoute: typeof ApiGenerateTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/': {
      id: '/api/conversations/'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/metadata': {
      id: '/api/projects/metadata'
      path: '/api/projects/metadata'
      fullPath: '/api/projects/metadata'
      preLoaderRoute: typeof ApiProjectsMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/api/projects/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id': {
      id: '/api/conversations/$id'
      path: '/api/conversations/$id'
      fullPath: '/api/conversations/$id'
      preLoaderRoute: typeof ApiConversationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/conversations': {
      id: '/api/projects/$id/conversations'
      path: '/conversations'
      fullPath: '/api/projects/$id/conversations'
      preLoaderRoute: typeof ApiProjectsIdConversationsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/add-conversation': {
      id: '/api/projects/$id/add-conversation'
      path: '/add-conversation'
      fullPath: '/api/projects/$id/add-conversation'
      preLoaderRoute: typeof ApiProjectsIdAddConversationRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/conversations/$id/share': {
      id: '/api/conversations/$id/share'
      path: '/share'
      fullPath: '/api/conversations/$id/share'
      preLoaderRoute: typeof ApiConversationsIdShareRouteImport
      parentRoute: typeof ApiConversationsIdRoute
    }
    '/api/conversations/$id/projects': {
      id: '/api/conversations/$id/projects'
      path: '/projects'
      fullPath: '/api/conversations/$id/projects'
      preLoaderRoute: typeof ApiConversationsIdProjectsRouteImport
      parentRoute: typeof ApiConversationsIdRoute
    }
    '/api/conversations/$id/messages': {
      id: '/api/conversations/$id/messages'
      path: '/messages'
      fullPath: '/api/conversations/$id/messages'
      preLoaderRoute: typeof ApiConversationsIdMessagesRouteImport
      parentRoute: typeof ApiConversationsIdRoute
    }
  }
}

interface ApiConversationsIdRouteChildren {
  ApiConversationsIdMessagesRoute: typeof ApiConversationsIdMessagesRoute
  ApiConversationsIdProjectsRoute: typeof ApiConversationsIdProjectsRoute
  ApiConversationsIdShareRoute: typeof ApiConversationsIdShareRoute
}

const ApiConversationsIdRouteChildren: ApiConversationsIdRouteChildren = {
  ApiConversationsIdMessagesRoute: ApiConversationsIdMessagesRoute,
  ApiConversationsIdProjectsRoute: ApiConversationsIdProjectsRoute,
  ApiConversationsIdShareRoute: ApiConversationsIdShareRoute,
}

const ApiConversationsIdRouteWithChildren =
  ApiConversationsIdRoute._addFileChildren(ApiConversationsIdRouteChildren)

interface ApiProjectsIdRouteChildren {
  ApiProjectsIdAddConversationRoute: typeof ApiProjectsIdAddConversationRoute
  ApiProjectsIdConversationsRoute: typeof ApiProjectsIdConversationsRoute
}

const ApiProjectsIdRouteChildren: ApiProjectsIdRouteChildren = {
  ApiProjectsIdAddConversationRoute: ApiProjectsIdAddConversationRoute,
  ApiProjectsIdConversationsRoute: ApiProjectsIdConversationsRoute,
}

const ApiProjectsIdRouteWithChildren = ApiProjectsIdRoute._addFileChildren(
  ApiProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  ProjectsRoute: ProjectsRoute,
  SharedRoute: SharedRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateTitleRoute: ApiGenerateTitleRoute,
  ApiShareRoute: ApiShareRoute,
  ChatIdRoute: ChatIdRoute,
  ProjectIdRoute: ProjectIdRoute,
  SIdRoute: SIdRoute,
  ShareIdRoute: ShareIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConversationsIdRoute: ApiConversationsIdRouteWithChildren,
  ApiProjectsIdRoute: ApiProjectsIdRouteWithChildren,
  ApiProjectsMetadataRoute: ApiProjectsMetadataRoute,
  ApiConversationsIndexRoute: ApiConversationsIndexRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
